services:
  koito-proxy:
    container_name: koito-proxy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KOITO_URL=http://localhost:4110
    volumes:
      - ./data:/app/data
    ports:
      - "4112:4112"
    restart: unless-stopped
    
    