services:
  koito-proxy:
    container_name: koito-proxy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROXY_PORT=4112
      - PROXY_DB=/app/data/koito.db
      - KOITO_URL=http://localhost:4110
    volumes:
      - ./data:/app/data
    ports:
      - "4112:4112"
    